version: "3.8"
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - immobilien-network

  php:
    image: mcakmak123/erp-immobilien-php:latest
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
    networks:
      - immobilien-network

  mysql:
    image: mysql:8.3
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: immobilien_erp
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - immobilien-network

networks:
  immobilien-network:
    driver: bridge

volumes:
  mysql-data:
